package(default_visibility = ["//visibility:public"])

cc_library(
    name = "copy",
    srcs = ["copy.cc"],
    hdrs = ["copy.h"],
    deps = [
        "//net/proxy:interface",
        "@com_google_absl//absl/container:fixed_array",
        "@com_google_absl//absl/functional:any_invocable",
    ],
)
