cc_binary(
    name = "base64",
    srcs = ["base64.cc"],
    deps = [
        "@com_google_absl//absl/strings",
        "@org_iceboy_trunk//base:flags",
        "@org_iceboy_trunk//io:file-utils",
        "@org_iceboy_trunk//io/posix:file",
    ]
)
