package(default_visibility = ["//visibility:public"])

cc_library(
    name = "reader",
    srcs = ["reader.cc"],
    hdrs = ["reader.h"],
    deps = [
        "@com_google_absl//absl/container:fixed_array",
        "@org_iceboy_trunk//net:asio",
    ],
)
