name: Release

on:
  push:
    tags: ["v*.*.*"]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu, aarch64-unknown-linux-gnu
      - uses: mlugg/setup-zig@v2
      - name: Install cargo-zigbuild
        run: cargo install cargo-zigbuild
      - name: Build
        run: |
          cargo zigbuild --target x86_64-unknown-linux-gnu --target aarch64-unknown-linux-gnu --release --bin proxy
          cp target/x86_64-unknown-linux-gnu/release/proxy proxy-rs-${GITHUB_REF_NAME}-linux-x86_64
          cp target/aarch64-unknown-linux-gnu/release/proxy proxy-rs-${GITHUB_REF_NAME}-linux-aarch64
      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            proxy-rs-v*.*.*-linux-x86_64
            proxy-rs-v*.*.*-linux-aarch64
