name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-linux-amd64:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install tools
        run: |
          sudo curl -fLo /usr/local/bin/bazel "https://github.com/bazelbuild/bazel/releases/download/6.5.0/bazel-6.5.0-linux-x86_64"
          sudo chmod +x /usr/local/bin/bazel
      - name: Build
        run: |
          bazel build -c opt net/tools:miracle-proxy
          ln bazel-bin/net/tools/miracle-proxy miracle-proxy-${GITHUB_REF_NAME}-linux-amd64
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            miracle-proxy-v*.*.*-linux-amd64

  build-linux-arm64:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install crossbuild-essential-arm64 -y
          sudo curl -fLo /usr/local/bin/bazel "https://github.com/bazelbuild/bazel/releases/download/6.0.0/bazel-6.0.0-linux-x86_64"
          sudo chmod +x /usr/local/bin/bazel
      - name: Build
        run: |
          bazel build -c opt --cpu=aarch64 --crosstool_top=//tools/bazel:toolchain --platforms=tools/bazel:linux-arm64 net/tools:miracle-proxy
          ln bazel-bin/net/tools/miracle-proxy miracle-proxy-${GITHUB_REF_NAME}-linux-arm64
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            miracle-proxy-v*.*.*-linux-arm64

  build-windows-amd64:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          bazel build -c opt net/tools:miracle-proxy
          Copy-Item bazel-bin\net\tools\miracle-proxy.exe -Destination miracle-proxy-$Env:GITHUB_REF_NAME-windows-amd64.exe
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            miracle-proxy-v*.*.*-windows-amd64.exe
