name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-linux-x86_64:
    runs-on: ubuntu-22.04
    container: debian:bullseye
    steps:
      - uses: actions/checkout@v3
      - name: Install tools
        run: |
          apt-get update
          apt-get install build-essential curl git -y
          curl -fLo /usr/local/bin/bazel "https://github.com/bazelbuild/bazel/releases/download/8.2.1/bazel-8.2.1-linux-x86_64"
          chmod +x /usr/local/bin/bazel
      - name: Build
        run: |
          bazel build -c opt net/tools:miracle-proxy
          cp bazel-bin/net/tools/miracle-proxy miracle-proxy-${GITHUB_REF_NAME}-linux-x86_64
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            miracle-proxy-v*.*.*-linux-x86_64

  build-linux-aarch64:
    runs-on: ubuntu-22.04
    container: debian:bullseye
    steps:
      - uses: actions/checkout@v3
      - name: Install tools
        run: |
          apt-get update
          apt-get install crossbuild-essential-arm64 curl git -y
          curl -fLo /usr/local/bin/bazel "https://github.com/bazelbuild/bazel/releases/download/8.2.1/bazel-8.2.1-linux-x86_64"
          chmod +x /usr/local/bin/bazel
      - name: Build
        run: |
          bazel build -c opt --platforms=@trunk//tools/platforms:linux-aarch64 net/tools:miracle-proxy
          cp bazel-bin/net/tools/miracle-proxy miracle-proxy-${GITHUB_REF_NAME}-linux-aarch64
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            miracle-proxy-v*.*.*-linux-aarch64

  build-windows-x86_64:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          bazel build -c opt net/tools:miracle-proxy
          Copy-Item bazel-bin\net\tools\miracle-proxy.exe -Destination miracle-proxy-$Env:GITHUB_REF_NAME-windows-x86_64.exe
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            miracle-proxy-v*.*.*-windows-x86_64.exe
