package(default_visibility = ["//visibility:public"])

cc_library(
    name = "endpoint",
    hdrs = ["endpoint.h"],
    deps = [
        "@com_google_absl//absl/strings",
        "@org_iceboy_trunk//net:asio",
    ],
)
